CREATE TABLE TBEMPLOYEE
(
  EMPLOYEE_ID     SERIAL       NOT NULL,
  LAST_NAME       VARCHAR(100) NOT NULL,
  FIRST_NAME      VARCHAR(100) NOT NULL,
  MIDDLE_NAME     VARCHAR(100),
  DATE_OF_BIRTH   DATE,
  EMAIL           VARCHAR(320),
  PHONE           VARCHAR(50),
  USER_ID         BIGINT,
  JOB_POSITION_ID BIGINT
);



ALTER TABLE TBEMPLOYEE ADD CONSTRAINT PK_TBEMPLOYEE
PRIMARY KEY (EMPLOYEE_ID);



CREATE TABLE TBUSER
(
  USER_ID      SERIAL       NOT NULL,
  LOGIN        VARCHAR(100) NOT NULL,
  PASSWORD     VARCHAR(100) NOT NULL,
  STATUS       BOOLEAN
);

ALTER TABLE TBUSER ADD CONSTRAINT PK_TBUSER
PRIMARY KEY (USER_ID);



CREATE TABLE TBROLE
(
  ROLE_ID      SERIAL       NOT NULL,
  ROLE_NAME    VARCHAR(100) NOT NULL,
  TITLE        VARCHAR(100) NOT NULL,
  DESCRIPTION  VARCHAR(200)
);

ALTER TABLE TBROLE ADD CONSTRAINT PK_TBROLE PRIMARY KEY (role_id);
ALTER TABLE TBROLE ADD CONSTRAINT UQ_TBROLE_NAME UNIQUE (role_name);
ALTER TABLE TBROLE ADD CONSTRAINT UQ_TBROLE_TITLE UNIQUE (title);



CREATE TABLE TBUSER_ROLE (
  USER_ID BIGINT NOT NULL,
  ROLE_ID BIGINT NOT NULL,
  CONSTRAINT PK_TBUSER_ROLES PRIMARY KEY (ROLE_ID, USER_ID)
);



CREATE TABLE TBPERMISSION
(
  PERMISSION_ID   SERIAL       NOT NULL,
  PERMISSION_NAME VARCHAR(100) NOT NULL,
  TITLE           VARCHAR(100) NOT NULL,
  DESCRIPTION     VARCHAR(200)
);

ALTER TABLE TBPERMISSION ADD CONSTRAINT PK_TBPERMISSION PRIMARY KEY (permission_id);
ALTER TABLE TBPERMISSION ADD CONSTRAINT UQ_TBPERMISSION_NAME UNIQUE (permission_name);
ALTER TABLE TBPERMISSION ADD CONSTRAINT UQ_TBPERMISSION_TITLE UNIQUE (title);



CREATE TABLE TBROLE_PERMISSION (
  ROLE_ID       BIGINT NOT NULL,
  PERMISSION_ID BIGINT NOT NULL,
  CONSTRAINT PK_TBROLE_PERMISSION PRIMARY KEY (ROLE_ID, PERMISSION_ID)
);